window.mongolianWords = [
    // Countries/Places
    { id: 1, word: "Хятад", difficulty: 1, category: "country" },
    { id: 2, word: "Солонгос", difficulty: 2, category: "country" },
    { id: 3, word: "Монгол", difficulty: 1, category: "country" },
    { id: 4, word: "Орос", difficulty: 1, category: "country" },
    { id: 5, word: "Энэтхэг", difficulty: 2, category: "country" },
    { id: 6, word: "Америк", difficulty: 2, category: "country" },
    { id: 7, word: "Япон", difficulty: 1, category: "country" },
    { id: 8, word: "Герман", difficulty: 2, category: "country" },
    { id: 9, word: "Франц", difficulty: 1, category: "country" },
    { id: 10, word: "Англи", difficulty: 1, category: "country" },

    // Nature
    { id: 11, word: "Нар", difficulty: 1, category: "nature" },
    { id: 12, word: "Сар", difficulty: 1, category: "nature" },
    { id: 13, word: "Ус", difficulty: 1, category: "nature" },
    { id: 14, word: "Гал", difficulty: 1, category: "nature" },
    { id: 15, word: "Мод", difficulty: 1, category: "nature" },
    { id: 16, word: "Өвс", difficulty: 1, category: "nature" },
    { id: 17, word: "Цэцэг", difficulty: 1, category: "nature" },
    { id: 18, word: "Уул", difficulty: 1, category: "nature" },
    { id: 19, word: "Чулуу", difficulty: 1, category: "nature" },
    { id: 20, word: "Шороо", difficulty: 1, category: "nature" },
    { id: 21, word: "Тэнгэр", difficulty: 2, category: "nature" },
    { id: 22, word: "Үүл", difficulty: 1, category: "nature" },
    { id: 23, word: "Бороо", difficulty: 2, category: "nature" },
    { id: 24, word: "Цас", difficulty: 1, category: "nature" },
    { id: 25, word: "Салхи", difficulty: 2, category: "nature" },

    // School/Education
    { id: 26, word: "Ном", difficulty: 1, category: "school" },
    { id: 27, word: "Сургууль", difficulty: 3, category: "school" },
    { id: 28, word: "Багш", difficulty: 1, category: "school" },
    { id: 29, word: "Сурагч", difficulty: 2, category: "school" },
    { id: 30, word: "Дэвтэр", difficulty: 2, category: "school" },
    { id: 31, word: "Үзэг", difficulty: 1, category: "school" },
    { id: 32, word: "Харандаа", difficulty: 3, category: "school" },
    { id: 33, word: "Шохой", difficulty: 2, category: "school" },
    { id: 34, word: "Самбар", difficulty: 2, category: "school" },
    { id: 35, word: "Анги", difficulty: 1, category: "school" },

    // Family
    { id: 36, word: "Аав", difficulty: 1, category: "family" },
    { id: 37, word: "Ах", difficulty: 1, category: "family" },
    { id: 38, word: "Эгч", difficulty: 1, category: "family" },
    { id: 39, word: "Дүү", difficulty: 1, category: "family" },
    { id: 40, word: "Ээж", difficulty: 1, category: "family" },
    { id: 41, word: "Өвөө", difficulty: 1, category: "family" },
    { id: 42, word: "Эмээ", difficulty: 1, category: "family" },
    { id: 43, word: "Нагац", difficulty: 2, category: "family" },
    { id: 44, word: "Авга", difficulty: 2, category: "family" },
    { id: 45, word: "Бэр", difficulty: 1, category: "family" },

    // Animals
    { id: 46, word: "Морь", difficulty: 1, category: "animals" },
    { id: 47, word: "Хонь", difficulty: 1, category: "animals" },
    { id: 48, word: "Ямаа", difficulty: 1, category: "animals" },
    { id: 49, word: "Үхэр", difficulty: 1, category: "animals" },
    { id: 50, word: "Тэмээ", difficulty: 2, category: "animals" },
    { id: 51, word: "Арслан", difficulty: 2, category: "animals" },
    { id: 52, word: "Бар", difficulty: 1, category: "animals" },
    { id: 53, word: "Чоно", difficulty: 1, category: "animals" },
    { id: 54, word: "Үнэг", difficulty: 1, category: "animals" },
    { id: 55, word: "Туулай", difficulty: 3, category: "animals" },
    { id: 56, word: "Баавгай", difficulty: 3, category: "animals" },
    { id: 57, word: "Ирвэс", difficulty: 2, category: "animals" },
    { id: 58, word: "Бүргэд", difficulty: 2, category: "animals" },
    { id: 59, word: "Шонхор", difficulty: 2, category: "animals" },
    { id: 60, word: "Хэрээ", difficulty: 2, category: "animals" },

    // Technlogy/Modern
    { id: 61, word: "Компьютер", difficulty: 4, category: "tech" },
    { id: 62, word: "Утас", difficulty: 1, category: "tech" },
    { id: 63, word: "Интернет", difficulty: 3, category: "tech" },
    { id: 64, word: "Тоглоом", difficulty: 3, category: "tech" },
    { id: 65, word: "Хөгжим", difficulty: 2, category: "tech" },
    { id: 66, word: "Телевиз", difficulty: 3, category: "tech" },
    { id: 67, word: "Радио", difficulty: 2, category: "tech" },
    { id: 68, word: "Машин", difficulty: 2, category: "tech" },
    { id: 69, word: "Онгоц", difficulty: 2, category: "tech" },
    { id: 70, word: "ГалтТэрэг", difficulty: 4, category: "tech" }, // Simplified string for game typing

    // Adjectives
    { id: 71, word: "Сайхан", difficulty: 2, category: "adjectives" },
    { id: 72, word: "Муухай", difficulty: 2, category: "adjectives" },
    { id: 73, word: "Өндөр", difficulty: 2, category: "adjectives" },
    { id: 74, word: "Намхан", difficulty: 2, category: "adjectives" },
    { id: 75, word: "Тарган", difficulty: 2, category: "adjectives" },
    { id: 76, word: "Туранхай", difficulty: 3, category: "adjectives" },
    { id: 77, word: "Баян", difficulty: 1, category: "adjectives" },
    { id: 78, word: "Ядуу", difficulty: 1, category: "adjectives" },
    { id: 79, word: "Хөгшин", difficulty: 2, category: "adjectives" },
    { id: 80, word: "Залуу", difficulty: 2, category: "adjectives" },

    // Verbs
    { id: 81, word: "Идэх", difficulty: 1, category: "verbs" },
    { id: 82, word: "Уух", difficulty: 1, category: "verbs" },
    { id: 83, word: "Унтах", difficulty: 2, category: "verbs" },
    { id: 84, word: "Сэрэх", difficulty: 2, category: "verbs" },
    { id: 85, word: "Явах", difficulty: 1, category: "verbs" },
    { id: 86, word: "Ирэх", difficulty: 1, category: "verbs" },
    { id: 87, word: "Гүйх", difficulty: 1, category: "verbs" },
    { id: 88, word: "Суух", difficulty: 1, category: "verbs" },
    { id: 89, word: "Босох", difficulty: 2, category: "verbs" },
    { id: 90, word: "Инээх", difficulty: 2, category: "verbs" },

    // Household
    { id: 91, word: "Ширээ", difficulty: 2, category: "household" },
    { id: 92, word: "Сандал", difficulty: 2, category: "household" },
    { id: 93, word: "Цонх", difficulty: 1, category: "household" },
    { id: 94, word: "Хаалга", difficulty: 2, category: "household" },
    { id: 95, word: "Байшин", difficulty: 2, category: "household" },
    { id: 96, word: "Гэр", difficulty: 1, category: "household" },
    { id: 97, word: "Ор", difficulty: 1, category: "household" },
    { id: 98, word: "Шүүгээ", difficulty: 2, category: "household" },
    { id: 99, word: "Төлөвлөгөө", difficulty: 4, category: "household" },
    { id: 100, word: "Зураг", difficulty: 2, category: "household" },

    // Colors
    { id: 101, word: "Улаан", difficulty: 2, category: "colors" },
    { id: 102, word: "Цагаан", difficulty: 2, category: "colors" },
    { id: 103, word: "Цэнхэр", difficulty: 2, category: "colors" },
    { id: 104, word: "Ногоон", difficulty: 2, category: "colors" },
    { id: 105, word: "Шар", difficulty: 1, category: "colors" },
    { id: 106, word: "Хар", difficulty: 1, category: "colors" },
    { id: 107, word: "Бор", difficulty: 1, category: "colors" },
    { id: 108, word: "Ягаан", difficulty: 2, category: "colors" },
    { id: 109, word: "Саарал", difficulty: 2, category: "colors" },
    { id: 110, word: "УлбарШар", difficulty: 3, category: "colors" },

    // Numbers/Time
    { id: 111, word: "Нэг", difficulty: 1, category: "time" },
    { id: 112, word: "Хоёр", difficulty: 1, category: "time" },
    { id: 113, word: "Гурав", difficulty: 2, category: "time" },
    { id: 114, word: "Дөрөв", difficulty: 2, category: "time" },
    { id: 115, word: "Тав", difficulty: 1, category: "time" },
    { id: 116, word: "Өглөө", difficulty: 2, category: "time" },
    { id: 117, word: "Өдөр", difficulty: 2, category: "time" },
    { id: 118, word: "Орой", difficulty: 2, category: "time" },
    { id: 119, word: "Шөнө", difficulty: 2, category: "time" },
    { id: 120, word: "Жил", difficulty: 1, category: "time" },

    // Food
    { id: 121, word: "Алим", difficulty: 1, category: "food" },
    { id: 122, word: "Жүрж", difficulty: 1, category: "food" },
    { id: 123, word: "Гадил", difficulty: 2, category: "food" },
    { id: 124, word: "Төмс", difficulty: 1, category: "food" },
    { id: 125, word: "Лууван", difficulty: 2, category: "food" },
    { id: 126, word: "Сонгино", difficulty: 3, category: "food" },
    { id: 127, word: "Сүү", difficulty: 1, category: "food" },
    { id: 128, word: "Тараг", difficulty: 2, category: "food" },
    { id: 129, word: "Аарц", difficulty: 2, category: "food" },
    { id: 130, word: "Мах", difficulty: 1, category: "food" },

    // Words with Ф, К, Ъ, Е, П, Ё, Ю
    { id: 131, word: "Ферм", difficulty: 1, category: "mixed" },
    { id: 132, word: "Фото", difficulty: 1, category: "mixed" },
    { id: 133, word: "Кофе", difficulty: 1, category: "mixed" },
    { id: 134, word: "Телефон", difficulty: 3, category: "mixed" },
    { id: 135, word: "Шкаф", difficulty: 1, category: "mixed" },
    { id: 136, word: "Кино", difficulty: 1, category: "mixed" },
    { id: 137, word: "Банк", difficulty: 1, category: "mixed" },
    { id: 138, word: "Парк", difficulty: 1, category: "mixed" },
    { id: 139, word: "Карт", difficulty: 1, category: "mixed" },
    { id: 140, word: "Кран", difficulty: 1, category: "mixed" },
    { id: 141, word: "Явъя", difficulty: 1, category: "mixed" },
    { id: 142, word: "Суръя", difficulty: 2, category: "mixed" },
    { id: 143, word: "Харъя", difficulty: 2, category: "mixed" },
    { id: 144, word: "Оръё", difficulty: 1, category: "mixed" },
    { id: 145, word: "Гаръя", difficulty: 2, category: "mixed" },
    { id: 146, word: "Ес", difficulty: 1, category: "mixed" },
    { id: 147, word: "Ерөөл", difficulty: 2, category: "mixed" },
    { id: 148, word: "Ертөнц", difficulty: 3, category: "mixed" },
    { id: 149, word: "Ерөнхий", difficulty: 3, category: "mixed" },
    { id: 150, word: "Еэвэн", difficulty: 2, category: "mixed" },
    { id: 151, word: "Пүрэв", difficulty: 2, category: "mixed" },
    { id: 152, word: "Пиво", difficulty: 1, category: "mixed" },
    { id: 153, word: "Пүрш", difficulty: 1, category: "mixed" },
    { id: 154, word: "Пүүз", difficulty: 1, category: "mixed" },
    { id: 155, word: "Сампин", difficulty: 2, category: "mixed" },
    { id: 156, word: "Ёс", difficulty: 1, category: "mixed" },
    { id: 157, word: "Ёроол", difficulty: 2, category: "mixed" },
    { id: 158, word: "Ёндоо", difficulty: 2, category: "mixed" },
    { id: 159, word: "Гоё", difficulty: 1, category: "mixed" },
    { id: 160, word: "Ёотон", difficulty: 2, category: "mixed" },
    { id: 161, word: "Юүлүүр", difficulty: 2, category: "mixed" },
    { id: 162, word: "Оюутан", difficulty: 3, category: "mixed" },
    { id: 163, word: "Аюул", difficulty: 2, category: "mixed" },
    { id: 164, word: "Юүдэн", difficulty: 2, category: "mixed" }
];
